### ISSUE TITLE
[FEAT] 함께 패킹리스트 카테고리 생성

### ISSUE THREAD

**Issue by dingding-21** [Team-Packman/Packman-Server#3]
## 📌Issue
함께 패킹리스트 카테고리 생성 구현

## 📝To-Do
- [x] requestBody의 name으로 카테고리 생성
- [x] 카테고리 생성 시 해당 카테고리 id 함께 패킹리스트의 카테고리 배열에 추가
- [x] populate를 통해 responseBody 구조 구현
