### ISSUE TITLE
[FIX] 날짜 생성 및 수정 TIME ZONE 관련

### ISSUE THREAD

**Issue by laalaa31** [Team-Packman/Packman-Server#37]
## 📌Issue
날짜 생성 및 수정 TIME ZONE 관련 수정
## 📝To-Do
- [ ] 함께 패킹리스트 생성
- [ ] 혼자 패킹리스트 생성
- [ ] 함께 패킹리스트 수정
