### ISSUE TITLE
[FEAT] 폴더 안 함께 패킹리스트 조회

### ISSUE THREAD

**Issue by hyeon-z** [Team-Packman/Packman-Server#61]
## 📌Issue
폴더 안 함께 패킹리스트 조회

## 📝To-Do
- [x] token으로 userId 찾기
- [x] userId로 유저의 함께 패킹리스트 폴더 찾기
- [x] folderId로 현재 폴더 찾기
- [x] 현재 폴더 안 패킹리스트 중 isDeleted = false인 리스트들 찾기
